name: Build Check
on:
  workflow_dispatch:

  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build-check.yml'
      - 'pyproject.toml'
      - 'setup.cfg'
      - 'setup.py'
      - 'MANIFEST.in'

  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/build-check.yml'
      - 'pyproject.toml'
      - 'setup.cfg'
      - 'setup.py'
      - 'MANIFEST.in'

jobs:
  build-check:
    uses: MAK-Relic-Tool/Workflows/.github/workflows/build-check.yml@main