name: MyPy

on:
  push:
    branches: [ main ]
    paths:
      - 'V2'
      - 'V5'
      - 'V7'
      - 'V9'
      - 'Core'
      - '.github/workflows/mypy.yml'
      - 'mypy.ini'

  pull_request:
    branches: [ main ]
    paths:
      - 'V2'
      - 'V5'
      - 'V7'
      - 'V9'
      - 'Core'
      - '.github/workflows/mypy.yml'
      - 'mypy.ini'
jobs:
  mypy:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]

    name: MyPy ${{ matrix.python-version }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade Pip
      run: |
        python -m pip install --upgrade pip

    - name: Install Wheel / Setuptools
      run: |
        python -m pip install wheel setuptools

    - name: Install MyPy
      run: |
        python -m pip install mypy

    - name: Install Repo
      run: |
        python -m pip install .

    - name: Run mypy
      run: |
        mypy --config-file mypy.ini --namespace-packages -p relic.sga