name: MyPy

on:
  workflow_dispatch:

  push:
    branches: [ main ]
    paths:
      - '.github/workflows/mypy.yml'  
      - 'mypy.ini'
      - 'setup.cfg'
      - 'setup.py'
      - 'MANIFEST.in'

  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/mypy.yml'
      - 'mypy.ini'
      - 'setup.cfg'
      - 'setup.py'
      - 'MANIFEST.in'

jobs:
  mypy:
    uses: MAK-Relic-Tool/Workflows/.github/workflows/mypy.yml@main
    with:
      package: "relic.sga"